[package]
name = "links"
version = "0.5.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.44"
clap = { git = "https://github.com/clap-rs/clap" }
hashbrown = "0.11.2"
linkex = { path = "../linkex" }
reqwest = { version = "0.11.4", features = ["blocking"] }
