[package]
name = "links"
version = "0.3.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

[dependencies]
linkex = { path = "../linkex" }
hashbrown = "0.11.2"
structopt = "0.3.21"
ureq = "2.1.0"
